name: Publish

on:
  push:
    branches:
      - jsr

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v1

      - name: Test
        run: deno task test

      - name: Publish package
        run: deno publish
