name: Release

on:
  push:
    tags:
      - v*

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.41.0

      - name: Test
        run: deno task test

  publish-to-jsr:
    name: Publish to JSR
    runs-on: ubuntu-latest
    needs: test

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v1

      - name: Publish to JSR
        run: deno publish

  publish-to-npm:
    name: Publish to npm
    runs-on: ubuntu-latest
    needs: publish-to-jsr

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare files
        run: mv npm/* .

      - name: Setup pnpm
        uses: pnpm/action-setup@v3

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          registry-url: 'https://registry.npmjs.org'
          cache: pnpm

      - name: Install
        run: pnpm install

      - name: Build
        run: pnpm run build

      - name: Publish to npm
        run: pnpm run version && pnpm publish --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  changelog:
    name: Changelog
    runs-on: ubuntu-latest
    needs: publish-to-jsr

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Deno
        uses: denoland/setup-deno@v1

      - name: Changelog
        run: deno run -A npm:changelogithub
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
